#!/usr/bin/env bash
# Creates one macvlan interface per virtual ONVIF camera, each carrying that
# camera's own MAC and IP so adopting clients see distinct network devices.
#
# The MAC/IP table is read from onvif.yml, generated by
# `nest-bridge onvif-config` from config.yaml, so this script cannot drift from
# the identity the ONVIF container advertises. Protect keys off MAC, and a
# mismatch between the two fails adoption.
#
# Idempotent: an interface that already has its target MAC and address is left
# untouched, so re-running does not drop the link of a camera Protect is
# recording.
set -euo pipefail

# Set PARENT to this host's LAN interface. Debian cloud images use eth0; hosts
# with predictable interface names use something like ens18 or enp1s0.
PARENT="${PARENT:-eth0}"
ONVIF_CONFIG="${ONVIF_CONFIG:-$(dirname "$(readlink -f "$0")")/onvif.yml}"

if [[ ! -r "$ONVIF_CONFIG" ]]; then
  echo "onvif config $ONVIF_CONFIG not found or unreadable;" \
       "generate it with: nest-bridge -config=config.yaml onvif-config > deploy/onvif.yml" >&2
  exit 1
fi

if ! ip link show "$PARENT" >/dev/null 2>&1; then
  echo "parent interface $PARENT not found (set PARENT to this host's LAN interface)" >&2
  exit 1
fi

# One "mac cidr" line per camera, in the order the ONVIF config declares them,
# which is the order that fixes each camera's onvif-N interface name.
mapfile -t CAMERAS < <(
  awk '
    /^virtual_cameras:/ { in_cams = 1; next }
    !in_cams           { next }
    /^[^[:space:]]/    { in_cams = 0; next }
    $1 == "mac:"       { gsub(/"/, "", $2); mac = $2; next }
    $1 == "ip:"        { gsub(/"/, "", $2); if (mac != "") { print mac, $2; mac = "" } }
  ' "$ONVIF_CONFIG"
)

if [[ ${#CAMERAS[@]} -eq 0 ]]; then
  echo "no virtual_cameras with a mac and ip found in $ONVIF_CONFIG" >&2
  exit 1
fi

# Without these, ARP flux makes every camera IP resolve to whichever macvlan
# child answers first, so all of them appear to Protect as one MAC.
# arp_ignore=1 answers only for addresses on the receiving interface;
# arp_announce=2 sources ARP requests from that interface's own address.
sysctl -qw net.ipv4.conf.all.arp_ignore=1
sysctl -qw net.ipv4.conf.all.arp_announce=2

# Remove interfaces left behind by a shorter camera list, before configuring the
# ones that remain. Dropping a camera renumbers the interfaces after it, so an
# address can move down to a lower-numbered child while the stale one still
# holds it. This has to run first: the kernel refuses the address as in use, and
# two children answering for one IP would make ARP resolution a race.
prune=$((${#CAMERAS[@]} + 1))
while ip link show "onvif-${prune}" >/dev/null 2>&1; do
  ip link del "onvif-${prune}"
  echo "onvif-${prune}  (removed: no longer in the camera list)"
  prune=$((prune + 1))
done

# When the camera list is reordered, target IPs and MACs can still be on the
# wrong onvif-N child. Free them before assigning so ip cannot fail with EEXIST.
for entry in "${CAMERAS[@]}"; do
  read -r mac cidr <<<"$entry"
  for other in /sys/class/net/onvif-*; do
    [[ -e "$other" ]] || continue
    other="${other##*/}"
    other_mac="$(cat "/sys/class/net/${other}/address" 2>/dev/null || true)"
    other_cidr="$(ip -4 -brief addr show dev "$other" 2>/dev/null | awk '{print $3}')"
    release_ip=false
    release_mac=false
    [[ "$other_cidr" == "$cidr" ]] && release_ip=true
    [[ "${other_mac,,}" == "${mac,,}" ]] && release_mac=true
    if ! $release_ip && ! $release_mac; then
      continue
    fi
    ip link set "$other" down 2>/dev/null || true
    if $release_ip; then
      ip addr flush dev "$other"
      echo "$other  $cidr  (preflight IP release)"
    fi
    if $release_mac; then
      temp_mac=$(printf '02:4e:53:54:fe:%02x' "$((10#${other#onvif-}))")
      ip link set "$other" address "$temp_mac"
      echo "$other  $mac  (preflight MAC release -> $temp_mac)"
    fi
  done
done

idx=0
for entry in "${CAMERAS[@]}"; do
  idx=$((idx + 1))
  read -r mac cidr <<<"$entry"
  dev="onvif-${idx}"

  ip link show "$dev" >/dev/null 2>&1 ||
    ip link add "$dev" link "$PARENT" type macvlan mode bridge

  have_mac="$(cat "/sys/class/net/${dev}/address" 2>/dev/null || true)"
  have_cidr="$(ip -4 -brief addr show dev "$dev" | awk '{print $3}')"

  # Comparison is case-insensitive: the kernel reports lower case, while the
  # generated config carries whatever case config.yaml used.
  if [[ "${have_mac,,}" == "${mac,,}" && "$have_cidr" == "$cidr" ]]; then
    echo "$dev  $mac  $cidr  (unchanged)"
    ip link set "$dev" up
    continue
  fi

  # The MAC must be set with the link down; some kernels reject it on a live link.
  ip link set "$dev" down
  ip link set "$dev" address "$mac"
  ip addr flush dev "$dev"
  ip addr add "$cidr" dev "$dev"
  ip link set "$dev" up

  echo "$dev  $mac  $cidr  (configured)"
done
